/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_restcomm_media_codec_ffmpeg_FFMPEGNative */

#ifndef _Included_org_restcomm_media_codec_ffmpeg_FFMPEGNative
#define _Included_org_restcomm_media_codec_ffmpeg_FFMPEGNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_restcomm_media_codec_ffmpeg_FFMPEGNative
 * Method:    createDecoder
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_org_restcomm_media_codec_ffmpeg_FFMPEGNative_createDecoder
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     org_restcomm_media_codec_ffmpeg_FFMPEGNative
 * Method:    decode
 * Signature: (J[S[B)I
 */
JNIEXPORT jint JNICALL Java_org_restcomm_media_codec_ffmpeg_FFMPEGNative_decode
  (JNIEnv *, jclass, jlong, jbyteArray, jbyteArray);

/*
 * Class:     org_restcomm_media_codec_ffmpeg_FFMPEGNative
 * Method:    destroyDecoder
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_restcomm_media_codec_ffmpeg_FFMPEGNative_destroyDecoder
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
